### ISSUE TITLE
Run test without googletest dependencies 

### ISSUE THREAD

**Issue by isratnisa** [google-research/sputnik#1]
I want to run the code for a single matrix without depending on googletest, e.g., something like "/.spmm [options] tmp.mtx". Is that possible with the current code? P.S. the code runs and passes all the test cases performed by spmm_test.

**Comment by tgale96** [comment]
Hi Israt! That is not currently supported, although we welcome contributions:)

If you'd like to create this yourself I'd recommend starting from the existing benchmarks for external matrices [here](https://github.com/google-research/sputnik/blob/os-build/sputnik/spmm/dlmc_benchmark.cu.cc). We haven't stabilized the public build yet so please let us know if you have any issues and we'll be happy to help!
